import type { Metadata, Viewport } from 'next'
import { ToastContainer } from "react-toastify"
import 'react-toastify/dist/ReactToastify.css'
import '../styles/globals.css'

export const viewport: Viewport = {
  themeColor: '#ffffff',
}

export const metadata: Metadata = {
  title: 'Mayank Joshi',
  description: 'Generated by Next.js',
  icons: {
    icon: [
      { url: '/images/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/images/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/images/favicon-96x96.png', sizes: '96x96', type: 'image/png' },
    ],
    apple: [
      { url: '/images/apple-icon-57x57.png', sizes: '57x57' },
      { url: '/images/apple-icon-60x60.png', sizes: '60x60' },
      { url: '/images/apple-icon-72x72.png', sizes: '72x72' },
      { url: '/images/apple-icon-76x76.png', sizes: '76x76' },
      { url: '/images/apple-icon-114x114.png', sizes: '114x114' },
      { url: '/images/apple-icon-120x120.png', sizes: '120x120' },
      { url: '/images/apple-icon-144x144.png', sizes: '144x144' },
      { url: '/images/apple-icon-152x152.png', sizes: '152x152' },
      { url: '/images/apple-icon-180x180.png', sizes: '180x180' },
    ],
    other: [
      {
        rel: 'icon',
        url: '/images/android-icon-192x192.png',
        sizes: '192x192',
        type: 'image/png',
      },
      {
        rel: 'manifest',
        url: '/images/manifest.json',
      },
    ],
  },
  other: {
    'msapplication-TileColor': '#ffffff',
    'msapplication-TileImage': '/images/ms-icon-144x144.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <ToastContainer
          position="bottom-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />
      </body>
    </html>
  )
}


